language: node_js
node_js:
- "node"
before_install:
- npm config set spin false
- npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
- npm install
script:
- echo "ON MASTER"
- |
  if [ -n "$TRAVIS_TAG" ]; then
    npm run build
  fi
- |
  if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
    bash npm run test
  fi
